env:
  es6: true
  node: true
extends:
  - "plugin:@typescript-eslint/recommended"
  - "prettier"
  - "prettier/@typescript-eslint"
parserOptions:
  ecmaVersion: 2018
rules:
  "@typescript-eslint/no-parameter-properties": off

